### ISSUE TITLE
Stuck on setting environment variable.

### ISSUE THREAD

**Issue by ngacho** [zatevakhin/obsidian-local-llm#3]
Hi, 
This is an awesome tool. Thank you, I'm trying to set up everything but I believe I'm setting environment variables wrong. Are you able to provide a more in depth clarification of setting everything up?

**Comment by ngacho** [comment]
I'm not sure what I should be referencing in this step `export MODEL=./models/7B/long_llama_3b.bin`

**Comment by zatevakhin** [comment]
Hi @ngacho! 

1. You need to download any model in `GGUF` format because the backend [`llama-cpp-python`](https://github.com/abetlen/llama-cpp-python) uses `GGUF` instead of `GGML` starting from version `0.1.79`. Check [TheBloke on HuggingFace](https://huggingface.co/TheBloke).
2. Put that model in some folder. For example, I have my models in `/home/user/.gguf-models`.
3. I exported my models like that:  `export MODEL=/home/user/.gguf-models/llama2-13b-Q4_K_M.gguf`
4. Then you can run server `python -m llama_cpp.server`.
5. You can use Obsidian to test the server or `curl` command.

```bash
curl -X 'POST' \
  'http://localhost:8000/v1/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt": "USER: What is Obsidian.md?\n\nASSISTANT:\n",
  "stream": false, "max_tokens": 256,
  "stop": []
}'
```

If you will be testing with curl, the answer should be in a similar format.
```
{"id":"cmpl-fa3f9466-d24b-4555-b82e-0b9c9da7f254","object":"text_completion","created":1694082389,"model":"/home/imartyniuk/.gguf-models/kimiko-v2-13b.Q4_K_M.gguf","choices":[{"text":"\nObsidian.md is a note-taking application that stores notes as plain text Markdown files and allows users to link them together in an interconnected graph format, facilitating organization, structuring, and accessing related information quickly. Obsidian is built using the JavaScript Electron framework and utilizes local storage for note data instead of relying on a cloud service.","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":20,"completion_tokens":79,"total_tokens":99}}
```

**Comment by ngacho** [comment]
Hi Thanks for that. That's amazing!!
